import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {join,resolve,extname} from 'node:path';
const root=resolve('.'),server=createServer((req,res)=>{try{const path=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=join(root,path==='/'?'index.html':path);if(!file.startsWith(root+'/'))throw Error();const type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.json':'application/json'}[extname(file)]||'text/plain';res.setHeader('Content-Type',type);res.end(readFileSync(file));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const profile=resolve('../.webtrade-test-profile'),errors=[],requests=[],passed=[];mkdirSync('tests/results',{recursive:true});
let context;const launch=()=>chromium.launchPersistentContext(profile,{headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox'],viewport:{width:1440,height:1000}});
function monitor(p){p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>requests.push({url:r.url(),method:r.method()}));}
const record=s=>{passed.push(s);console.log('PASS:',s);};
try{
context=await launch();let p=await context.newPage();monitor(p);await p.goto(base);await p.locator('#results .card').first().waitFor();assert.equal(await p.locator('#results .card').count(),18);assert((await p.locator('#resultCount').innerText()).includes('1 000')||(await p.locator('#resultCount').innerText()).includes('1 000'));await p.locator('#results img').first().waitFor();await p.waitForFunction(()=>document.querySelector('#results img').complete&&document.querySelector('#results img').naturalWidth>0);record('Catalog, pagination and local SVG images load');
await p.locator('#search').fill('Aetherion');assert.equal(await p.locator('#results .card').count(),18);await p.locator('[name=manufacturer]').selectOption('Aetherion');await p.locator('[name=propulsion]').selectOption('Plazmahajtás');assert((await p.locator('#resultCount').innerText()).includes('11'));await p.locator('#sort').selectOption('price');await p.locator('[data-action=reset]').click();record('Live search, combined filters, sorting, reset');
await p.locator('#accountButton').click();await p.locator('[data-action=auth-register]').click();await p.locator('[name=username]').fill('TesterOne');await p.locator('[name=password]').fill('FuturePass123');await p.locator('[name=confirm]').fill('FuturePass123');await p.locator('#authForm .primary').click();await p.waitForFunction(()=>!document.querySelector('#dialog').open);assert((await p.locator('#accountButton').innerText()).includes('TesterOne'));record('UI registration with PBKDF2');
const checks=await p.evaluate(async()=>{const d=await import('./storage.js');const out={};try{await d.register('testerone','OtherPass123','OtherPass123');out.duplicate=false;}catch{out.duplicate=true;}try{await d.login('TesterOne','wrong');out.incorrect=false;}catch{out.incorrect=true;}const a=await d.get('accounts','testerone');out.secure=!('password'in a)&&a.hash.length===64&&a.salt.length===16&&a.iterations>=310000;return out;});assert.deepEqual(checks,{duplicate:true,incorrect:true,secure:true});record('Duplicate usernames and incorrect passwords rejected; no plaintext passwords');
await p.locator('#results .card').first().locator('[data-action=favorite]').click();await p.waitForTimeout(100);await p.locator('#results .card').first().locator('[data-action=compare-add]').click();await p.locator('#results .card').nth(1).locator('[data-action=compare-add]').click();await p.locator('[data-nav=compare]').click();await p.locator('.compare-table').waitFor();assert.equal(await p.locator('.compare-table thead td').count(),2);record('Persistent favorites and side-by-side comparison');
await p.goto(base+'/#vehicle/WT-0002');await p.locator('#galleryMain').waitFor();await p.locator('[data-angle="1"]').click();assert((await p.locator('#galleryMain').getAttribute('src')).endsWith('WT-0002-1'));await p.locator('[data-action=contact]').click();await p.locator('#contactForm textarea').fill('Érdeklődöm a kitalált autó iránt.');await p.locator('#contactForm .primary').click();await p.locator('.success h2').waitFor();await p.locator('[data-action=close]').click();record('Details, multi-view gallery, seller contact simulation');
await p.locator('[data-action=buy]').click();await p.locator('[name=holder]').fill('Fictional Explorer');await p.locator('[name=number]').fill('0000000000000000');await p.locator('[name=month]').fill('00');await p.locator('[name=year]').fill('3000');await p.locator('[name=cvv]').fill('fiction');await p.locator('[name=remember]').check();await p.locator('#paymentForm .primary').click();await p.getByText('PAYMENT SUCCESSFUL',{exact:true}).waitFor();assert((await p.locator('.receipt').innerText()).includes('WT3000-'));const receiptDownload=p.waitForEvent('download');await p.locator('[data-action=receipt-download]').click();const download=await receiptDownload;assert(download.suggestedFilename().endsWith('.txt'));await p.locator('[data-action=open-garage]').click();await p.locator('#accountContent .card').waitFor();assert.equal(await p.locator('#accountContent .card').count(),1);record('Fictional arbitrary card payment, success, receipt download, garage');
const stored=await p.evaluate(async()=>{const d=await import('./storage.js'),v=(await import('./catalog.js')).catalog[1];let twice=false;try{await d.purchase('testerone',v,{number:'0000000000000000'});}catch{twice=true;}const profile=await d.profile('testerone');return {twice,own:(await d.get('ownership',v.id)).user,purchases:(await d.all('purchases')).length,cards:profile.cards,favorites:profile.favorites.length,recent:profile.recent.length};});assert(stored.twice);assert.equal(stored.own,'testerone');assert.equal(stored.purchases,1);assert.deepEqual(stored.cards,[{label:'Fiktív demókártya',last4:'0000'}]);assert.equal(stored.favorites,1);assert(stored.recent>0);await p.reload();await p.locator('#accountContent .card').waitFor();record('Sold ownership, duplicate purchase prevention, masked metadata, reload persistence');
await context.close();context=await launch();p=await context.newPage();monitor(p);await p.goto(base+'/#garage');await p.locator('#accountContent .card').waitFor();assert((await p.locator('#accountButton').innerText()).includes('TesterOne'));assert.equal(await p.locator('#accountContent .card').count(),1);const loginRestart=await p.evaluate(async()=>{const d=await import('./storage.js');return (await d.login('TesterOne','FuturePass123')).username;});assert.equal(loginRestart,'TesterOne');record('Actual Chromium process restart preserves account, password and garage');
await p.locator('[data-action=account-tab][data-id=listings]').click();await p.locator('[data-action=new-listing]').click();await p.locator('[name=manufacturer]').fill('Test Galactic');await p.locator('[name=model]').fill('Demo Racer');await p.locator('[name=description]').fill('Képzeletbeli galaktikus autó a helyi automatizált teszthez.');const png=Buffer.from(await p.evaluate(()=>{const c=document.createElement('canvas');c.width=100;c.height=60;const x=c.getContext('2d');x.fillStyle='#44ccee';x.fillRect(0,0,100,60);return c.toDataURL('image/png').split(',')[1];}),'base64');await p.locator('#imageUpload').setInputFiles([{name:'test.png',mimeType:'image/png',buffer:png},{name:'test2.png',mimeType:'image/png',buffer:png}]);await p.locator('#uploadPreview img').nth(1).waitFor();await p.locator('[data-action=preview-listing]').click();await p.locator('#listingPreview h3').first().waitFor();await p.locator('#listingForm button[type=submit]').click();await p.locator('#accountContent .card').waitFor();assert.equal(await p.locator('#accountContent .card').count(),1);await p.locator('[data-action=edit]').click();await p.locator('[name=model]').fill('Demo Racer II');await p.locator('#listingForm button[type=submit]').click();await p.getByText('Demo Racer II',{exact:true}).waitFor();record('Listing creation, multiple uploads/compression, preview, publication and editing');
const exportEvent=p.waitForEvent('download');await p.locator('[data-action=export]').click();const exported=await exportEvent,exportPath=await exported.path(),exportText=readFileSync(exportPath,'utf8'),exportJSON=JSON.parse(exportText);assert.equal(exportJSON.listings.length,1);assert(!exportText.includes('hash'));assert(exportJSON.listings[0].images[0].startsWith('data:image/webp'));await p.locator('[data-action=import]').click();await p.locator('#importForm [name=file]').setInputFiles({name:'export.json',mimeType:'application/json',buffer:Buffer.from(exportText)});await p.locator('#importForm .primary').click();await p.waitForFunction(()=>document.querySelectorAll('#accountContent .card').length===2);record('Listing export/import with fresh IDs and compressed local images');
await p.locator('[data-action=delete]').first().click();await p.locator('[data-action=delete-confirm]').click();await p.waitForFunction(()=>document.querySelectorAll('#accountContent .card').length===1);await p.locator('[data-action=sold]').click();await p.waitForFunction(()=>document.querySelector('[data-action=edit]').disabled);record('Own listing deletion and sold marking');
const isolation=await p.evaluate(async()=>{const d=await import('./storage.js');await d.register('TesterTwo','SecondPass123','SecondPass123');const l=(await d.all('listings'))[0];let editBlocked=false,deleteBlocked=false;try{await d.saveListing('testertwo',{...l,status:'Elérhető'});}catch{editBlocked=true;}try{await d.deleteListing('testertwo',l.id);}catch{deleteBlocked=true;}const [a,b]=await Promise.all([(await import('./catalog.js')).catalog,(await import('./catalog.js')).catalog]);const results=await Promise.allSettled([d.purchase('testerone',a[2],{number:'1111111111111111'}),d.purchase('testertwo',b[2],{number:'2222222222222222'})]);const p2=await d.profile('testertwo');return {editBlocked,deleteBlocked,fulfilled:results.filter(x=>x.status==='fulfilled').length,emptyFavorites:p2.favorites.length===0};});assert.deepEqual(isolation,{editBlocked:true,deleteBlocked:true,fulfilled:1,emptyFavorites:true});record('User data separation, ownership checks and atomic concurrent purchase');
await p.locator('[data-action=logout]').click();await p.locator('#results').waitFor();await p.locator('#accountButton').click();await p.locator('[name=username]').fill('TesterTwo');await p.locator('[name=password]').fill('SecondPass123');await p.locator('#authForm .primary').click();await p.waitForFunction(()=>!document.querySelector('#dialog').open);await p.goto(base+'/#garage');await p.locator('#accountContent').waitFor();const p2count=await p.locator('#accountContent .card').count();assert(p2count<=1);await p.goto(base+'/#vehicle/WT-0002');await p.locator('[data-action=buy]').waitFor();assert(await p.locator('[data-action=buy]').isDisabled());record('Different account login and sold vehicle cannot be bought through UI');
await p.goto(base+'/#account');await p.locator('[data-action=account-tab][data-id=settings]').click();await p.locator('#theme').selectOption('violet');await p.locator('[name=current]').fill('SecondPass123');await p.locator('[name=next]').fill('ChangedPass123');await p.locator('#passwordForm [name=confirm]').fill('ChangedPass123');await p.locator('#passwordForm .primary').click();await p.waitForTimeout(500);const changed=await p.evaluate(async()=>{const d=await import('./storage.js');return (await d.login('TesterTwo','ChangedPass123')).id;});assert.equal(changed,'testertwo');assert.equal(await p.locator('body').getAttribute('data-theme'),'violet');record('Password change and persistent neon preferences');
await p.goto(base);await p.locator('#search').fill('Veylora');await p.locator('[data-action=save-search]').click();await p.locator('#savedSearches button').waitFor();await p.locator('[data-action=reset]').click();await p.locator('#savedSearches button').click();await p.waitForFunction(()=>document.querySelector('#search').value==='Veylora');await p.locator('[data-action=stats]').click();await p.locator('.bar-row').first().waitFor();assert.equal(await p.locator('.bar-row').count(),36);record('Saved search/history and manufacturer/price statistics');
await p.goto(base);await p.locator('#results').waitFor();await p.screenshot({path:'tests/results/desktop.png',fullPage:true});await p.setViewportSize({width:390,height:844});await p.reload();await p.locator('#results').waitFor();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('.filters summary').click();await p.locator('[name=manufacturer]').selectOption('Veylora');await p.screenshot({path:'tests/results/mobile.png',fullPage:true});await p.setViewportSize({width:820,height:1180});await p.reload();await p.locator('#results').waitFor();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));record('Desktop, 390px mobile and 820px tablet responsive layouts');
const allImages=await p.evaluate(async()=>{const {catalog,imageFor}=await import('./catalog.js');for(let i=0;i<catalog.length;i+=25){for(let angle=0;angle<3;angle++){await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>img.naturalWidth?resolve():reject(Error('empty image'));img.onerror=()=>reject(Error('broken image '+i));img.src=imageFor(catalog[i],angle);});}}return true;});assert(allImages);record('All 40 static SVG asset sheets and three gallery angles load');
assert.equal(errors.length,0,errors.join('\n'));assert(requests.every(r=>r.url.startsWith(base)||r.url.startsWith('data:')));assert(requests.every(r=>r.method==='GET'));record('No JavaScript errors, no external requests, no real payment requests');
writeFileSync('tests/results/report.json',JSON.stringify({passed,errors,requests:requests.length,browser:'Chromium',mobile:'390×844 emulation; not a physical Android 16 device'},null,2));
}catch(e){console.error(e);writeFileSync('tests/results/report.json',JSON.stringify({passed,errors,failure:e.stack},null,2));if(context){try{await context.pages().at(-1).screenshot({path:'tests/results/failure.png',fullPage:true});}catch{}}process.exitCode=1;}finally{if(context)await context.close();server.close();}
