// Stable, additive schema. No account or purchase data is cleared during upgrades.
export const DB_NAME='webtrade-3000';
export const PBKDF_ITERATIONS=310000;
let db;
const request=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
export async function openDB(){if(db)return db;db=await new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{for(const name of ['accounts','profiles','listings','purchases','ownership','settings'])if(!r.result.objectStoreNames.contains(name))r.result.createObjectStore(name,{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error('Zárd be a régi Webtrade lapokat az adatbázis frissítéséhez.'));});db.onversionchange=()=>{db.close();db=null;};return db;}
export async function get(store,id){return request((await openDB()).transaction(store).objectStore(store).get(id));}
export async function all(store){return request((await openDB()).transaction(store).objectStore(store).getAll());}
export async function write(store,value){const d=await openDB();return new Promise((resolve,reject)=>{const t=d.transaction(store,'readwrite');t.objectStore(store).put(value);t.oncomplete=()=>resolve(value);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||new Error('A mentés megszakadt.'));});}
const hex=a=>Array.from(new Uint8Array(a),b=>b.toString(16).padStart(2,'0')).join('');
async function hash(password,salt,iterations=PBKDF_ITERATIONS){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:new Uint8Array(salt),iterations,hash:'SHA-256'},key,256));}
export async function register(username,password,confirm){username=username.trim();if(!/^[\p{L}\p{N}_-]{3,32}$/u.test(username))throw new Error('A felhasználónév 3–32 betű, szám, kötőjel vagy aláhúzás lehet.');if(password.length<8)throw new Error('Legalább 8 karakteres jelszó szükséges.');if(password!==confirm)throw new Error('A két jelszó nem egyezik.');const id=username.toLocaleLowerCase('hu'),salt=Array.from(crypto.getRandomValues(new Uint8Array(16))),record={id,username,salt,hash:await hash(password,salt),iterations:PBKDF_ITERATIONS};const d=await openDB();await new Promise((resolve,reject)=>{const t=d.transaction('accounts','readwrite');t.objectStore('accounts').add(record);t.oncomplete=resolve;t.onabort=()=>reject(new Error(t.error?.name==='ConstraintError'?'Ez a felhasználónév már foglalt.':'A fiók mentése sikertelen.'));});return record;}
export async function login(username,password){const a=await get('accounts',username.trim().toLocaleLowerCase('hu'));if(!a||await hash(password,a.salt,a.iterations)!==a.hash)throw new Error('Hibás felhasználónév vagy jelszó.');return a;}
export async function changePassword(id,current,next,confirm){const a=await get('accounts',id);await login(a.username,current);if(next.length<8||next!==confirm)throw new Error('Az új jelszó legalább 8 karakteres legyen, és egyezzen a megerősítéssel.');const salt=Array.from(crypto.getRandomValues(new Uint8Array(16)));return write('accounts',{...a,salt,hash:await hash(next,salt),iterations:PBKDF_ITERATIONS});}
export async function profile(id){return await get('profiles',id)||{id,favorites:[],recent:[],searches:[],cards:[],theme:'cyan'};}
export async function updateProfile(id,patch){const d=await openDB();return new Promise((resolve,reject)=>{const t=d.transaction('profiles','readwrite'),s=t.objectStore('profiles'),r=s.get(id);r.onsuccess=()=>{const p=r.result||{id,favorites:[],recent:[],searches:[],cards:[],theme:'cyan'};s.put({...p,...(typeof patch==='function'?patch(p):patch),id});};t.oncomplete=resolve;t.onabort=()=>reject(t.error);});}
export async function saveListing(user,v){const d=await openDB();return new Promise((resolve,reject)=>{const t=d.transaction(['listings','ownership'],'readwrite'),s=t.objectStore('listings'),r=s.get(v.id),o=t.objectStore('ownership').get(v.id);let old,owned,ready=0;function apply(){if(++ready<2)return;if((old&&old.owner!==user)||owned){t.abort();return;}s.put({...v,owner:user,source:'user'});}r.onsuccess=()=>{old=r.result;apply();};o.onsuccess=()=>{owned=o.result;apply();};t.oncomplete=resolve;t.onabort=()=>reject(new Error('Ez a hirdetés nem szerkeszthető (más tulajdonos vagy már megvásárolt jármű).'));});}
export async function deleteListing(user,id){const d=await openDB();return new Promise((resolve,reject)=>{const t=d.transaction(['listings','ownership'],'readwrite'),s=t.objectStore('listings'),r=s.get(id),o=t.objectStore('ownership').get(id);let v,owned,n=0;function apply(){if(++n<2)return;if(!v||v.owner!==user||owned){t.abort();return;}s.delete(id);}r.onsuccess=()=>{v=r.result;apply();};o.onsuccess=()=>{owned=o.result;apply();};t.oncomplete=resolve;t.onabort=()=>reject(new Error('A hirdetés nem törölhető.'));});}
export async function purchase(user,vehicle,card){
 // Payment input is deliberately NOT persisted. Only label and last4 can be saved.
 const d=await openDB();return new Promise((resolve,reject)=>{
 const t=d.transaction(['accounts','listings','ownership','purchases','profiles'],'readwrite');let receipt,reason='A vásárlás mentése sikertelen.';
 const a=t.objectStore('accounts').get(user);a.onsuccess=()=>{if(!a.result){reason='Jelentkezz be.';t.abort();return;}const l=t.objectStore('listings').get(vehicle.id);l.onsuccess=()=>{const v=l.result||vehicle;if(v.source==='user'&&!l.result||v.status!=='Elérhető'||v.owner===user){reason='A jármű nem vásárolható meg.';t.abort();return;}const o=t.objectStore('ownership'),r=o.get(v.id);r.onsuccess=()=>{if(r.result){reason='A járművet már megvásárolták.';t.abort();return;}const id='WT3000-'+crypto.randomUUID().toUpperCase();receipt={id,user,vehicle:{...v,images:v.images||[]},amount:v.price,date:new Date().toISOString(),status:'COMPLETED',demo:true};o.add({id:v.id,user,transaction:id});t.objectStore('purchases').add(receipt);if(l.result)t.objectStore('listings').put({...v,status:'Eladva'});if(card.remember){const s=t.objectStore('profiles'),p=s.get(user);p.onsuccess=()=>{const value=p.result||{id:user,favorites:[],recent:[],searches:[],cards:[],theme:'cyan'};value.cards=[{label:'Fiktív demókártya',last4:card.number.slice(-4)}];s.put(value);};}};};};
 t.oncomplete=()=>resolve(receipt);t.onabort=()=>reject(new Error(reason));t.onerror=()=>{};
 });
}
export async function compressImage(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024)throw new Error('JPG, PNG vagy WebP képet válassz (legfeljebb 15 MB).');const bitmap=await createImageBitmap(file);const ratio=Math.min(1,1200/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/webp',.8);}
